theme: minima
title: test-site
author: Sav Est
email: se1285@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
  new description 

# social links
twitter_username: 
github_username:  savannahestridge

show_excerpts: true # set to false to remove excerpts on the homepage
